collections:
  - name: community.general
  - name: community.windows
  - name: servicenow.itsm
  - name: ansible.windows
  - name: ansible.controller
    version: 4.2.0
  - name: redhat_cop.controller_configuration
    version: 2.2.0
  - name: azure.azcollection
