---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Get cat fact
    ansible.builtin.uri:
      url: https://catfact.ninja/fact
    register: cat_fact
  
  - name: Set fact vars
    set_fact:
      LegalNoticeCaption: "Cat Fact of The Day"
      LegalNoticeText: "{{ cat_fact.json.fact }}"

  - name: Print cat_fact
    debug:
      var: LegalNoticeText
