---
- hosts: localhost
  gather_facts: false
  ansible_connection: local
  tasks:
  - name: Get cat fact
    ansible.builtin.uri:
      url: https://catfact.ninja/fact
    register: cat_fact
  
  - name: Print cat_fact
    debug:
      var: cat_fact
