---
- name: Create Azure Windows VM
  hosts: localhost
  connection: local
  tasks:
    - name: Generate dynamic names for resources
      set_fact:
        public_ip_name: "{{ vm_name.replace('-','_') }}_ip_name"
        nic_name: "{{ vm_name.replace('-','_') }}_nic"
        admin_password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1) }}"

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        os_type: Windows
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "{{ nic_name }}"
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: "{{ vm_sku }}"
          version: latest
        tags:
          deployment: ansible
          purpose: demo
          os: windows
        winrm:
          - protocol: https
          - certificate_url: https://demo6754893265973824234.vault.azure.net/secrets/winrm/35dc3e8151ed495f87c4207709dac6ac
          - source_vault: /subscriptions/ede7f891-835c-4128-af5b-0e53848e54e7/resourceGroups/openenv-bf2nq/providers/Microsoft.KeyVault/vaults/demo6754893265973824234
      register: vm_facts

    - name: Setting IP fact
      set_fact:
        public_ip: "{{ vm_facts.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"

    - name: VM access information
      debug:
        msg: 
          - "Username: {{ admin_user }}"
          - "Password: {{ admin_password }}"
          - "Public IP: {{ public_ip }}"

    - name: Create a configuration item
      servicenow.itsm.configuration_item:
        name: "{{ vm_name }}"
        short_description: "Windows Server Azure VM at {{ public_ip }}"
        sys_class_name: cmdb_ci_server
        assigned_to: "{{ requested_for }}"
        environment: production
        category: Hardware
        other:
          model_number: "{{ vm_sku }}"
        instance:
          host: "{{ SN_HOST }}"
          grant_type: "password"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
      when: SN_USERNAME is defined
