---
- name: Create Azure Windows VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "{{ vnet_cidr }}"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_cidr }}"
        virtual_network: "{{ vnet_name }}"

    - name: Create Network Security Group that allows SSH and RDP
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: RDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1002
            direction: Inbound

    - name: Generate dynamic names for resources
      set_fact:
        public_ip_name: "{{ vm_name.replace('-','_') }}_ip_name"
        nic_name: "{{ vm_name.replace('-','_') }}_nic"
        admin_password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1) }}"

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        os_type: Windows
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_user }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "{{ nic_name }}"
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: "{{ vm_sku }}"
          version: latest
        tags:
          deployment: ansible
          purpose: demo
      register: vm_facts

    - name: Setting IP fact
      set_fact:
        public_ip: "{{ vm_facts.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"

    - name: VM access information
      debug:
        msg: 
          - "Username: {{ admin_user }}"
          - "Password: {{ admin_password }}"
          - "Public IP: {{ public_ip }}"

    - name: Create a configuration item
      servicenow.itsm.configuration_item:
        name: "{{ vm_name }}"
        short_description: "Windows Server Azure VM at {{ public_ip }}"
        sys_class_name: cmdb_ci_server
        assigned_to: "{{ requested_for }}"
        environment: production
        category: Hardware
        other:
          model_number: "{{ vm_sku }}"
        instance:
          host: "{{ SN_HOST }}"
          grant_type: "password"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
