---
- name: Configure File Server
  hosts: os_windows
  vars:
    top_level_share: 'C:\branch_share\'
    department_level_shares:
      - "{{ top_level_share }}Accounting"
      - "{{ top_level_share }}IT"
      - "{{ top_level_share }}Facilities"

  tasks:
  - name: Create standard shares
    ansible.windows.win_file:
      path: "{{ item }}"
      state: present
    loop: {{ department_level_shares }}

  - name: Install file server features
    ansible.windows.win_feature:
      name:
      - FS-FileServer
      - FS-Resource-Manager
      state: present
    register: feature_status

  - name: Reboot when feature requires it
    ansible.windows.win_reboot:
    when: feature_status.reboot_required
