---
- name: Security Settings
  hosts: os_windows
  vars:
    LegalNoticeCaption: undef
    LegalNoticeText: undef
  tasks:
  - name: Update PowerShellGet
    win_shell: | 
      Install-PackageProvider -Name NuGet -Force
      Install-Module -Name PowerShellGet -Force
  
  - name: Setup the SecurityPolicyDSC module
    community.windows.win_psmodule:
      name: SecurityPolicyDSC
      module_version: 2.10.0.0
      state: present
  
  - name: Set password history
    ansible.windows.win_dsc:
      resource_name: AccountPolicy
      Name: Enforce_password_history
      Enforce_password_history: 24

  - name: Set maximum password age
    ansible.windows.win_dsc:
      resource_name: AccountPolicy
      Name: Maximum_Password_Age
      Maximum_Password_Age: 60

  - name: Set minimum password age
    ansible.windows.win_dsc:
      resource_name: AccountPolicy
      Name: Minimum_Password_Age
      Maximum_Password_Age: 20

  - name: Set minimum password length
    ansible.windows.win_dsc:
      resource_name: AccountPolicy
      Name: Minimum_Password_Length
      Maximum_Password_Age: 8

  - name: Set password complexity requirements
    ansible.windows.win_dsc:
      resource_name: AccountPolicy
      Name: Password_must_meet_complexity_requirements
      Password_must_meet_complexity_requirements: Enabled

  - name: Change legal notice caption
    ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
      name: LegalNoticeCaption
      data: "{{ LegalNoticeCaption }}"
      type: string
      state: present

  - name: Change legal notice text
    ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
      name: LegalNoticeText
      data: "{{ LegalNoticeText }}"
      type: string
      state: present

  - name: Create a change task
    servicenow.itsm.change_request_task:
      configuration_item: snow_configuration_item
      change_request_number: snow_change_request
      assigned_to: "{{ SN_USERNAME }}"
      state: closed
      close_code: "successful"
      close_notes: "Applied company standard password policy"
      short_description: Apply security settings to web server
      description: Configure password policy
      instance:
        host: "{{ SN_HOST }}"
        grant_type: "password"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
