---
- name: SNOW Close Change Request
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Close change_request
    servicenow.itsm.change_request:
      instance:
        host: "{{ SN_HOST }}"
        grant_type: "password"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
      state: closed
      close_code: "successful"
      close_notes: "Closed"
      assignment_group: Network
      number: "{{ snow_change_request }}"
