---
- name: SNOW Create Change Request
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create change request
    servicenow.itsm.change_request:
      instance:
        host: "{{ SN_HOST }}"
        grant_type: "password"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
      type: "{{ survey_type }}"
      state: "{{ survey_state }}"
      requested_by: "{{ survey_requested_by }}"
      short_description: "{{ survey_short_description }}"
      description: "{{ survey_description }}"
      priority: "{{ survey_priority }}"
      risk: "{{ survey_risk }}"
      impact: "{{ survey_impact }}"
    register: snow_change_request

  - name: Set stats
    set_stats:
      data:
        snow_change_request: "{{ snow_configuration_item.record.name }}"
