---
- hosts: os_windows
  vars:
    - site_source: "{{ survey_site_source | default('https://www.free-css.com/assets/files/free-css-templates/download/page281/koppee.zip') }}"
    - iis_root: C:\Inetpub\wwwroot
    - site_dest: "{{ iis_root }}\\source.zip"

  tasks:
  - name: Install IIS
    win_feature:
      name: Web-Server
      state: present

  - name: Start IIS service
    win_service:
      name: W3Svc
      state: started

  - name: Remove default IIS files
    win_file:
      path: "{{ iis_root }}\\{{ item }}"
      state: absent
    loop:
      - "iisstart.htm"
      - "iisstart.png"

  - name: Download site source
    win_get_url:
      url: "{{ site_source }}"
      dest: "{{ site_dest }}"

  - name: Extract site content
    win_unzip:
      src: "{{ site_dest }}"
      dest: "{{ iis_root }}"
      delete_archive: yes

  - name: Create a change task
    servicenow.itsm.change_request_task:
      configuration_item: "{{ snow_configuration_item.record.name }}"
      change_request_number: "{{ snow_change_request.record.number }}"
      assigned_to: "{{ SN_USERNAME }}"
      state: closed
      close_code: "successful"
      close_notes: "Configured IIS and deployed the content from {{ survey_site_source }}"
      short_description: Configure web server
      description: Configure IIS and deploy content
      instance:
        host: "{{ SN_HOST }}"
        grant_type: "password"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"

  - name: Get site dir
    win_shell: "(Get-ChildItem -Path {{ iis_root }}).Name"
    register: site_sub_dir

  - name: Output URL
    debug:
      msg: "http://{{ ansible_host }}/{{ site_sub_dir.stdout_lines[0] }}"
