---
- hosts: "{{ HOSTS | default('localhost') }}"
  gather_facts: no
  vars:
    controller_validate_certs: false
    demo: azure
  vars_files:
    - "{{demo}}/azure_vars.yml"
    - "{{demo}}/setup.yml"
  tasks:
    - name: Setup Components
      include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ controller_components }}"
      when:
        - controller_components | d("") | length > 0

    - name: Print Message
      debug:
        msg: "{{ user_message }}"
      when: user_message is defined
