---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: Remove VM and all resources that were autocreated
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vm_name }}"
      remove_on_absent: all_autocreated
      state: absent
